[package]
name = "ising-montecarlo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4.27"
rand = "0.9.1"
rayon = "1.10.0"

[[bin]]
name = "simulation"
path = "src/bin/simulation.rs"
